# Generated by Django 2.2.6 on 2020-01-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0003_task_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
