# Generated by Django 2.2.6 on 2020-01-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0005_auto_20200122_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
