# Generated by Django 2.2.8 on 2020-02-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0008_auto_20200204_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unique_view_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
