# Generated by Django 2.2.8 on 2020-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0011_auto_20200206_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='unique_view_id',
            field=models.SlugField(max_length=8, unique=True),
        ),
    ]
